### ISSUE TITLE
Continuation cannot be 'played' more than once in comprehension

### ISSUE THREAD

**Issue by d-plaindoux** [d-plaindoux/pilin#7]
The following code 
```kotlin
(with(Continuation.monad<Int>().infix) {
    continuation<Int, Int> { k -> k(2) + k(2) } bind { a ->
        pure(38) map { b ->
            a + b
        }
    }
}) { it + 3 }
```
produces the expected value 86 since the continuation is played twice.
Unfortunately, this code expressed with the comprehension:
```kotlin
(Comprehension<Continuation.TK<Int>, Int>(Continuation.monad()) {
    val (a) = continuation<Int, Int> { k -> k(2) + k(2) }
    val (b) = pure(38)
    a + b
}) { it + 3 }
```
 do not work and crashes because it relies on Kotlin suspended block.
```
java.lang.IllegalStateException: Already resumed
	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
	at io.smallibs.pilin.extension.Comprehension$bind$$inlined$let$lambda$1$1.invokeSuspend(Comprehension.kt:41)
	at io.smallibs.pilin.extension.Comprehension$bind$$inlined$let$lambda$1$1.invoke(Comprehension.kt)
       ....
```

**Comment by d-plaindoux** [comment]
Comprehension do not use anymore Kotlin coroutine and continuation
